### ISSUE TITLE
Run tslint as part of builds

### ISSUE THREAD

**Issue by philjones88** [AngularClass/lib-starter#3]
Notice you have a tslint.json file (which works in VS code nicely) but should really run it at build time too

**Comment by Hendrixer** [comment]
yea, I agree, PR?

**Comment by philjones88** [comment]
I'll have to wait till the rimraf PR is merged.

I'll install the npm package and set a new script `tslint` to run.

Then alter `build` and `release` scripts to also run the new `tslint` script.
