### ISSUE TITLE
Issue with package paths

### ISSUE THREAD

**Issue by philjones88** [AngularClass/lib-starter#7]
I published https://github.com/VQComms/angularx-logger based on this template.

One interesting issue I found was that to include sub files I had to do like:

`import { Logger } from 'angularx-logger/logger';`

Until I changed `"module": "angularx-logger.module.js"` to `"module": "index.js"`

Then I could do:

`import { Logger } from 'angularx-logger';`

I don't understand all the different modules etc. I just wanted to make it easy to use and this after a few attempts (1.0.0 to 1.0.7) was the simplest solution I could find.

**Comment by Hendrixer** [comment]
yea, looks like I typoed that, nice find!

**Comment by Hendrixer** [comment]
`"module":` is used by bundlers like Webpack 2 and rollup for tree shaking. Instead of providing the bundled file, it is instead a transpiled version to ES5 with ES2015 module syntax. This allows tree shaking.

**Comment by philjones88** [comment]
Did you want a PR to correct it?

**Comment by Hendrixer** [comment]
sure!
